import React from 'react';
import {
    CommandCenterIcon, CodeExplainerIcon, FeatureBuilderIcon, RegexSandboxIcon, SnippetVaultIcon, CssGridEditorIcon,
    JsonTreeIcon, XbrlConverterIcon, UnitTestGeneratorIcon, PromptCraftPadIcon, CodeFormatterIcon, SchemaDesignerIcon,
    PwaManifestEditorIcon, MarkdownSlidesIcon, ScreenshotToComponentIcon, TypographyLabIcon, SvgPathEditorIcon,
    StyleTransferIcon, CodingChallengeIcon, CodeReviewBotIcon, AiPullRequestAssistantIcon, ChangelogGeneratorIcon,
    CronJobBuilderIcon, AsyncCallTreeIcon, AudioToCodeIcon, CodeDiffGhostIcon, CodeSpellCheckerIcon, ColorPaletteGeneratorIcon,
    LogicFlowBuilderIcon, MetaTagEditorIcon, NetworkVisualizerIcon, ResponsiveTesterIcon, SassCompilerIcon, ImageGeneratorIcon,
    CommitGeneratorIcon, ConnectionsIcon, ProjectExplorerIcon, CodeMigratorIcon, ThemeDesignerIcon, GitLogAnalyzerIcon,
    ConcurrencyAnalyzerIcon, WebScraperIcon, UserStoryGeneratorIcon, UrlEncoderIcon, UmlDiagramGeneratorIcon,
    TerraformConfigGeneratorIcon, SystemDesignPlannerIcon, SslCertificateInspectorIcon, SshKeyGeneratorIcon, SqlFormatterIcon,
    SecurityVulnerabilityScannerIcon, ReleaseNotesGeneratorIcon, ProjectTimelineGeneratorIcon, ProductRoadmapGeneratorIcon, PhotoIcon, GitBranchIcon,
    PerformanceLoadTesterIcon, MockDataGeneratorIcon, LogoGeneratorIcon, KubernetesManifestGeneratorIcon, LandingPageGeneratorIcon, JwtDebuggerIcon,
    JsonSchemaGeneratorIcon, JsonCsvConverterIcon, InterviewPrepKitIcon, HtmlTableGeneratorIcon, GitHubRepoExplorerIcon,
    GithubProfileReadmeGeneratorIcon, GitBranchingModelVisualizerIcon, EyeIcon,
    ErrorMessageExplainerIcon, EnvironmentVariableManagerIcon, EmailTemplateBuilderIcon, DockerfileGeneratorIcon,
    DigitalWhiteboardIcon, DocumentTextIcon, DesignPatternSuggesterIcon, DependencyUpdateSuggesterIcon,
    DataStructureVisualizerIcon, DatabaseQueryGeneratorIcon, CustomerSupportBotBuilderIcon, ColorContrastCheckerIcon,
    CodeToFlowchartIcon, CodeSnippetToApiIcon, CodePerformanceAnalyzerIcon, CodeObfuscatorIcon, CodeDocumentationGeneratorIcon,
    CodeDependencyVisualizerIcon, CodeCommentGeneratorIcon, CloudCostEstimatorIcon, CiCdGeneratorIcon, Base64EncoderIcon,
    ApiSdkGeneratorIcon, ApiDocsGeneratorIcon, ApiClientIcon, AiTechBlogWriterIcon, AccessibilityCheckerIcon,
    GithubIcon,
    MagnifyingGlassIcon
} from './icons.tsx';

// Omit the 'component' property, as it will be added dynamically.
type RawFeature = {
  id: string;
  name: string;
  description: string;
  icon: React.ReactNode;
  category: string;
  aiConfig?: {
    model: string;
    systemInstruction?: string;
  };
};

export const RAW_FEATURES: RawFeature[] = [
    { id: 'ai-command-center', name: 'AI Command Center', description: 'Natural language control for the entire toolkit.', icon: <CommandCenterIcon />, category: 'Core' },
    { id: 'ai-feature-builder', name: 'AI Feature Builder', description: 'Generate code files for a new feature from a prompt.', icon: <FeatureBuilderIcon />, category: 'Core' },
    { id: 'project-explorer', name: 'Project Explorer', description: 'Browse and view files in your connected repository.', icon: <ProjectExplorerIcon />, category: 'Core' },
    { id: 'connections', name: 'Connections', description: 'Connect to GitHub to manage repositories.', icon: <ConnectionsIcon />, category: 'Core' },
    { id: 'ai-code-explainer', name: 'AI Code Explainer', description: 'Get a detailed, structured analysis of any code snippet.', icon: <CodeExplainerIcon />, category: 'AI Tools' },
    { id: 'theme-designer', name: 'AI Theme Designer', description: 'Generate a UI color theme from a description.', icon: <ThemeDesignerIcon />, category: 'AI Tools' },
    { id: 'ai-commit-generator', name: 'AI Commit Generator', description: 'Generate a conventional commit message from a git diff.', icon: <CommitGeneratorIcon />, category: 'AI Tools' },
    { id: 'ai-unit-test-generator', name: 'AI Unit Test Generator', description: 'Generate unit tests for your code or components.', icon: <UnitTestGeneratorIcon />, category: 'AI Tools' },
    { id: 'ai-code-migrator', name: 'AI Code Migrator', description: 'Translate code between different languages and frameworks.', icon: <CodeMigratorIcon />, category: 'AI Tools' },
    { id: 'ai-pr-assistant', name: 'AI PR Assistant', description: 'Generate a PR summary from code changes and populate a template.', icon: <AiPullRequestAssistantIcon />, category: 'AI Tools' },
    { id: 'ai-image-generator', name: 'AI Image Generator', description: 'Generate high-quality images from text prompts.', icon: <ImageGeneratorIcon />, category: 'AI Tools' },
    { id: 'logo-generator', name: 'AI Logo Generator', description: 'Generate a vector-style logo from a description.', icon: <LogoGeneratorIcon />, category: 'AI Tools' },
    { id: 'ai-repo-creator', name: 'AI Repo Creator', description: 'Describe your project to create a new GitHub repository.', icon: <GithubIcon />, category: 'AI Tools' },
    { id: 'ai-tech-blog-writer', name: 'AI Tech Blog Writer', description: 'Generate a draft for a technical blog post from a topic.', icon: <AiTechBlogWriterIcon />, category: 'AI Tools' },
    { id: 'ai-style-transfer', name: 'AI Code Style Transfer', description: 'Rewrite code to match a specific style guide.', icon: <StyleTransferIcon />, category: 'AI Tools' },
    { id: 'ai-coding-challenge-generator', name: 'AI Coding Challenge', description: 'Generate a unique coding problem to test your skills.', icon: <CodingChallengeIcon />, category: 'AI Tools' },
    { id: 'css-grid-editor', name: 'CSS Grid Editor', description: 'Visually create and configure CSS grid layouts.', icon: <CssGridEditorIcon />, category: 'Frontend' },
    { id: 'pwa-manifest-editor', name: 'PWA Manifest Editor', description: 'Configure and generate the manifest.json file for your PWA.', icon: <PwaManifestEditorIcon />, category: 'Frontend' },
    { id: 'screenshot-to-component', name: 'Screenshot to Component', description: 'Generate React/Tailwind code from a UI screenshot.', icon: <ScreenshotToComponentIcon />, category: 'Frontend' },
    { id: 'color-palette-generator', name: 'Color Palette Generator', description: 'Generate a harmonious color palette from a base color.', icon: <ColorPaletteGeneratorIcon />, category: 'Frontend' },
    { id: 'meta-tag-editor', name: 'Meta Tag Editor', description: 'Generate SEO & social media meta tags with a live preview.', icon: <MetaTagEditorIcon />, category: 'Frontend' },
    { id: 'responsive-tester', name: 'Responsive Tester', description: 'Preview web pages at different screen sizes.', icon: <ResponsiveTesterIcon />, category: 'Frontend' },
    { id: 'sass-scss-compiler', name: 'SASS/SCSS Compiler', description: 'A real-time SASS/SCSS to CSS compiler.', icon: <SassCompilerIcon />, category: 'Frontend' },
    { id: 'html-table-generator', name: 'HTML Table Generator', description: 'Generate an HTML table from CSV data.', icon: <HtmlTableGeneratorIcon />, category: 'Frontend' },
    { id: 'font-preview-picker', name: 'Font Previewer', description: 'Preview Google Fonts and get CSS import rules.', icon: <EyeIcon />, category: 'Frontend' },
    { id: 'font-pairing-tool', name: 'Font Pairing Tool', description: 'Preview Google Font combinations for headings and body text.', icon: <EyeIcon />, category: 'Frontend' },
    { id: 'typography-lab', name: 'Typography Lab', description: 'Experiment with font pairings and preview them.', icon: <TypographyLabIcon />, category: 'Frontend' },
    { id: 'svg-path-editor', name: 'SVG Path Editor', description: 'Visually create and manipulate SVG path data.', icon: <SvgPathEditorIcon />, category: 'Frontend' },
    { id: 'email-template-builder', name: 'Email Template Builder', description: 'Visually build a responsive HTML email template.', icon: <EmailTemplateBuilderIcon />, category: 'Frontend' },
    { id: 'color-contrast-checker', name: 'Color Contrast Checker', description: 'Check if color combinations meet WCAG accessibility standards.', icon: <ColorContrastCheckerIcon />, category: 'Frontend' },
    { id: 'landing-page-generator', name: 'AI Landing Page Generator', description: 'Generate a complete HTML landing page from a description.', icon: <LandingPageGeneratorIcon />, category: 'Frontend' },
    { id: 'regex-sandbox', name: 'RegEx Sandbox', description: 'Test regular expressions and generate them with AI.', icon: <RegexSandboxIcon />, category: 'Testing' },
    { id: 'worker-thread-debugger', name: 'AI Concurrency Analyzer', description: 'Analyze JS for Web Worker concurrency issues.', icon: <ConcurrencyAnalyzerIcon />, category: 'Testing' },
    { id: 'jwt-debugger', name: 'JWT Debugger', description: 'Decode and inspect JSON Web Tokens.', icon: <JwtDebuggerIcon />, category: 'Testing' },
    { id: 'performance-load-tester', name: 'Performance Load Tester', description: 'Simulate load tests to visualize performance metrics.', icon: <PerformanceLoadTesterIcon />, category: 'Testing' },
    { id: 'api-client', name: 'API Client', description: 'Make HTTP requests to any API endpoint.', icon: <ApiClientIcon />, category: 'Testing' },
    { id: 'schema-designer', name: 'Schema Designer', description: 'Visually design your database schema with drag-and-drop.', icon: <SchemaDesignerIcon />, category: 'Database' },
    { id: 'database-query-generator', name: 'AI SQL Query Generator', description: 'Generate SQL queries from natural language.', icon: <DatabaseQueryGeneratorIcon />, category: 'Database' },
    { id: 'sql-formatter', name: 'AI SQL Formatter', description: 'Clean up and format your SQL queries for readability.', icon: <SqlFormatterIcon />, category: 'Database' },
    { id: 'mock-data-generator', name: 'AI Mock Data Generator', description: 'Generate mock JSON data from a description.', icon: <MockDataGeneratorIcon />, category: 'Data' },
    { id: 'json-tree-navigator', name: 'JSON Tree Navigator', description: 'Visualize JSON data as a collapsible tree.', icon: <JsonTreeIcon />, category: 'Data' },
    { id: 'xbrl-converter', name: 'XBRL Converter', description: 'Convert a JSON object into a simplified XBRL-like XML format.', icon: <XbrlConverterIcon />, category: 'Data' },
    { id: 'json-schema-generator', name: 'AI JSON Schema Generator', description: 'Generate a JSON Schema from a sample JSON object.', icon: <JsonSchemaGeneratorIcon />, category: 'Data' },
    { id: 'json-csv-converter', name: 'JSON <> CSV Converter', description: 'A simple utility to convert between JSON arrays and CSV.', icon: <JsonCsvConverterIcon />, category: 'Data' },
    { id: 'base64-encoder', name: 'Base64 Encoder/Decoder', description: 'A simple utility to encode to and decode from Base64.', icon: <Base64EncoderIcon />, category: 'Data' },
    { id: 'url-encoder', name: 'URL Encoder/Decoder', description: 'Encode or decode strings for use in URLs.', icon: <UrlEncoderIcon />, category: 'Data' },
    { id: 'portable-snippet-vault', name: 'Snippet Vault', description: 'Store, search, and enhance your reusable code snippets.', icon: <SnippetVaultIcon />, category: 'Productivity' },
    { id: 'prompt-craft-pad', name: 'Prompt Craft Pad', description: 'Create, save, and manage your favorite AI prompts.', icon: <PromptCraftPadIcon />, category: 'Productivity' },
    { id: 'markdown-slideshow-generator', name: 'Markdown to Slides', description: 'Write markdown, present it as a slideshow.', icon: <MarkdownSlidesIcon />, category: 'Productivity' },
    { id: 'interview-prep-kit', name: 'AI Interview Prep Kit', description: 'Generate common interview questions and answers for a topic.', icon: <InterviewPrepKitIcon />, category: 'Productivity' },
    { id: 'github-profile-readme-generator', name: 'AI GitHub README Generator', description: 'Generate a professional GitHub profile README.', icon: <GithubProfileReadmeGeneratorIcon />, category: 'Productivity' },
    { id: 'digital-whiteboard', name: 'Digital Whiteboard', description: 'Organize your ideas with interactive sticky notes.', icon: <DigitalWhiteboardIcon />, category: 'Productivity' },
    { id: 'dev-notes-sticky-panel', name: 'Dev Notes', description: 'Jot down quick notes, reminders, and to-dos.', icon: <DocumentTextIcon />, category: 'Productivity' },
    { id: 'project-moodboard', name: 'Project Moodboard', description: 'Organize your project ideas with interactive sticky notes.', icon: <PhotoIcon />, category: 'Productivity' },
    { id: 'cron-job-builder', name: 'AI Cron Job Builder', description: 'Visually construct a cron expression or describe it in plain English.', icon: <CronJobBuilderIcon />, category: 'Deployment' },
    { id: 'terraform-config-generator', name: 'AI Terraform Generator', description: 'Describe cloud resources to generate Terraform HCL code.', icon: <TerraformConfigGeneratorIcon />, category: 'Deployment' },
    { id: 'kubernetes-manifest-generator', name: 'AI K8s Manifest Generator', description: 'Describe your service to generate Kubernetes YAML manifests.', icon: <KubernetesManifestGeneratorIcon />, category: 'Deployment' },
    { id: 'dockerfile-generator', name: 'AI Dockerfile Generator', description: 'Describe your application to get a production-ready Dockerfile.', icon: <DockerfileGeneratorIcon />, category: 'Deployment' },
    { id: 'ci-cd-generator', name: 'AI CI/CD Generator', description: 'Generate a CI/CD pipeline configuration from a description.', icon: <CiCdGeneratorIcon />, category: 'Deployment' },
    { id: 'cloud-cost-estimator', name: 'AI Cloud Cost Estimator', description: 'Get a high-level monthly cost estimate for infrastructure.', icon: <CloudCostEstimatorIcon />, category: 'Deployment' },
    { id: 'environment-variable-manager', name: 'ENV Manager', description: 'Load, edit, and download .env files securely on your machine.', icon: <EnvironmentVariableManagerIcon />, category: 'Deployment' },
    { id: 'ssl-certificate-inspector', name: 'SSL Certificate Inspector', description: 'Paste a PEM-encoded certificate to inspect its details.', icon: <SslCertificateInspectorIcon />, category: 'Security' },
    { id: 'ssh-key-generator', name: 'SSH KeyGen Helper', description: 'Generate a secure ssh-keygen command to run on your machine.', icon: <SshKeyGeneratorIcon />, category: 'Security' },
    { id: 'security-vulnerability-scanner', name: 'AI Security Scanner', description: 'Perform a static analysis of code for common vulnerabilities.', icon: <SecurityVulnerabilityScannerIcon />, category: 'Security' },
    { id: 'accessibility-checker', name: 'AI Accessibility Checker', description: 'Paste HTML to get an AI-powered accessibility audit.', icon: <AccessibilityCheckerIcon />, category: 'Security' },
    { id: 'visual-git-tree', name: 'Visual Git Tree', description: 'Visualize git history and get an AI summary from git log.', icon: <GitLogAnalyzerIcon />, category: 'Workflow' },
    { id: 'linter-formatter', name: 'AI Code Formatter', description: 'Clean up your code with AI-powered formatting.', icon: <CodeFormatterIcon />, category: 'Workflow' },
    { id: 'web-scraper', name: 'AI Web Scraper', description: 'Paste HTML and describe the data you want to extract.', icon: <WebScraperIcon />, category: 'Workflow' },
    { id: 'user-story-generator', name: 'AI User Story Generator', description: 'Describe a feature to generate user stories.', icon: <UserStoryGeneratorIcon />, category: 'Workflow' },
    { id: 'system-design-planner', name: 'AI System Design Planner', description: 'Describe an application to generate a high-level system design.', icon: <SystemDesignPlannerIcon />, category: 'Workflow' },
    { id: 'project-timeline-generator', name: 'AI Project Timeline Generator', description: 'Generate a high-level project timeline from a description.', icon: <ProjectTimelineGeneratorIcon />, category: 'Workflow' },
    { id: 'pr-generator', name: 'PR Generator', description: 'Draft a professional pull request from a structured template.', icon: <GitBranchIcon />, category: 'Workflow' },
    { id: 'logic-flow-builder', name: 'Logic Flow Builder', description: 'Visually build application logic flows and pipelines.', icon: <LogicFlowBuilderIcon />, category: 'Workflow' },
    { id: 'git-branching-model-visualizer', name: 'Git Branching Visualizer', description: 'An educational tool to visualize common Git workflows.', icon: <GitBranchingModelVisualizerIcon />, category: 'Workflow' },
    { id: 'design-pattern-suggester', name: 'AI Design Pattern Suggester', description: 'Get relevant design pattern suggestions for a problem.', icon: <DesignPatternSuggesterIcon />, category: 'Workflow' },
    { id: 'code-to-flowchart', name: 'AI Code to Flowchart', description: 'Visualize your code\'s logic by generating a flowchart.', icon: <CodeToFlowchartIcon />, category: 'Workflow' },
    { id: 'code-review-bot', name: 'AI Code Review Bot', description: 'Get an automated code review from Gemini.', icon: <CodeReviewBotIcon />, category: 'Workflow' },
    { id: 'code-performance-analyzer', name: 'AI Performance Analyzer', description: 'Get AI-powered suggestions to optimize your code.', icon: <CodePerformanceAnalyzerIcon />, category: 'Workflow' },
    { id: 'code-documentation-generator', name: 'AI Docs Generator', description: 'Generate markdown documentation from your source code.', icon: <CodeDocumentationGeneratorIcon />, category: 'Workflow' },
    { id: 'code-dependency-visualizer', name: 'AI Dependency Visualizer', description: 'Get an AI-powered breakdown of your dependencies.', icon: <CodeDependencyVisualizerIcon />, category: 'Workflow' },
    { id: 'code-comment-generator', name: 'AI Comment Generator', description: 'Automatically add explanatory comments to your code.', icon: <CodeCommentGeneratorIcon />, category: 'Workflow' },
    { id: 'changelog-generator', name: 'AI Changelog Generator', description: 'Generate a markdown changelog from your raw git log.', icon: <ChangelogGeneratorIcon />, category: 'Workflow' },
    { id: 'api-sdk-generator', name: 'AI API SDK Generator', description: 'Generate a client SDK from an OpenAPI spec.', icon: <ApiSdkGeneratorIcon />, category: 'Workflow' },
    { id: 'api-docs-generator', name: 'AI API Docs Generator', description: 'Generate markdown documentation from API endpoint code.', icon: <ApiDocsGeneratorIcon />, category: 'Workflow' },
    { id: 'release-notes-generator', name: 'AI Release Notes Generator', description: 'Generate release notes from commit messages.', icon: <ReleaseNotesGeneratorIcon />, category: 'Workflow' },
    { id: 'product-roadmap-generator', name: 'AI Product Roadmap Generator', description: 'Generate a structured roadmap from product goals.', icon: <ProductRoadmapGeneratorIcon />, category: 'Workflow' },
    { id: 'uml-diagram-generator', name: 'AI UML Diagram Generator', description: 'Describe a system to generate a UML diagram.', icon: <UmlDiagramGeneratorIcon />, category: 'Workflow' },
    { id: 'dependency-update-suggester', name: 'AI Dependency Suggester', description: 'Get AI-powered dependency update suggestions.', icon: <DependencyUpdateSuggesterIcon />, category: 'Workflow' },
    { id: 'error-message-explainer', name: 'AI Error Explainer', description: 'Get a clear explanation for a confusing error message.', icon: <ErrorMessageExplainerIcon />, category: 'Workflow' },
    { id: 'async-call-tree-viewer', name: 'Async Call Tree Viewer', description: 'Visualize an asynchronous function call tree.', icon: <AsyncCallTreeIcon />, category: 'Workflow' },
    { id: 'audio-to-code', name: 'AI Audio-to-Code', description: 'Speak your programming ideas and watch them turn into code.', icon: <AudioToCodeIcon />, category: 'Workflow' },
    { id: 'code-diff-ghost', name: 'Code Diff Ghost', description: 'Visualize code changes with a "ghost typing" effect.', icon: <CodeDiffGhostIcon />, category: 'Workflow' },
    { id: 'code-spell-checker', name: 'Code Spell Checker', description: 'Finds and highlights common typos in code.', icon: <CodeSpellCheckerIcon />, category: 'Workflow' },
    { id: 'code-snippet-to-api', name: 'AI Snippet to API', description: 'Turn any code snippet into a simple API endpoint.', icon: <CodeSnippetToApiIcon />, category: 'Workflow' },
    { id: 'code-obfuscator', name: 'Code Obfuscator', description: 'Make your JavaScript code harder to read.', icon: <CodeObfuscatorIcon />, category: 'Workflow' },
    { id: 'customer-support-bot-builder', name: 'AI Support Bot Builder', description: 'Generate a system prompt for a support chatbot.', icon: <CustomerSupportBotBuilderIcon />, category: 'Workflow' },
    { id: 'data-structure-visualizer', name: 'Data Structure Visualizer', description: 'Visualize graph data structures.', icon: <DataStructureVisualizerIcon />, category: 'Workflow' },
    { id: 'github-repo-explorer', name: 'GitHub Repo Explorer', description: 'Find and view public repositories for any GitHub user.', icon: <MagnifyingGlassIcon />, category: 'Workflow' },
];